version: "3.5"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d:ro
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: always

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=example@mail.com
    restart: always

  glob3d-nginx:
    image: nginx:latest
    container_name: glob3d-nginx
    depends_on:
      - glob3d-client
      - glob3d-server
    volumes:
      - ./nginx:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=domain1.name,domain2.name
      - LETSENCRYPT_HOST=domain1.name,domain2.name
    restart: always

  glob3d-client:
    image: glob3d-client
    container_name: glob3d-client
    stdin_open: true
    ports:
      - 3000:3000
    restart: always

  glob3d-server:
    image: glob3d-server
    container_name: glob3d-server
    ports:
      - 5000:5000
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:3.6.23-xenial
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  certs:
  vhost:
  html:
  acme:
  mongo-data:
    driver: local
