# nginx and certbot setup: https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
version: "3.5"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - glob3d
    depends_on:
      - client
      - server
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - glob3d
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  client:
    image: glob3d-client
    container_name: client
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - glob3d

  server:
    image: glob3d-server
    container_name: server
    ports:
      - 5000:5000
    networks:
      - glob3d
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.23-xenial
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - glob3d
    volumes:
      - mongo-data:/data/db

networks:
  glob3d:
    driver: bridge

volumes:
  mongo-data:
    driver: local
