/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: premudraya (https://sketchfab.com/premudraya)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-assets-c5f2e7eacc0f4e659c4188925fcb84f1
title: Low poly assets
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'

export default function FlowerBush(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF('/assets.gltf');
    const pos = {
        x: props.position[0],
        y: props.position[1]+0.8,
        z: props.position[2]
    };
    return (
        <group ref={group} dispose={null}>
            {props.color === "blue" ?
            <group position={[pos.x, pos.y, pos.z]} rotation={[-1.06, 0.06, 0.28]} scale={[0.1, 0.1, 0.1]}>
            <mesh material={materials['Material.001']} geometry={nodes.mesh_17.geometry} />
            </group> :
            <group position={[pos.x, pos.y, pos.z]} rotation={[-1.06, 0.06, 0.28]} scale={[0.1, 0.1, 0.1]}>
            <mesh material={materials['Material.001']} geometry={nodes.mesh_16.geometry} />
            </group>}
        </group>
    );
}

useGLTF.preload('/assets.gltf')