/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Anskar (https://sketchfab.com/Anskar)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-grass-pack-2ffb4d5302c14d038eaf6488b8c7ede2
title: Low Poly Grass Pack
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'

export default function Grass(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/grass.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <group position={[56.82, 0, 128.37]} rotation={[-Math.PI / 2, 0, 0.33]} scale={[3.91, 3.91, 5.19]}>
            <mesh material={materials.Grass} geometry={nodes.Circle018_Grass_0.geometry} />
          </group>
          <group position={[-55.15, 0, 133.25]} rotation={[-Math.PI / 2, 0, 0.83]} scale={[3.15, 3.15, 5.72]}>
            <mesh material={materials.Grass} geometry={nodes.Circle015_Grass_0.geometry} />
          </group>
          <group position={[62.16, 0, 1.3]} rotation={[-Math.PI / 2, 0, 1.29]} scale={[3.97, 3.97, 7.21]}>
            <mesh material={materials.Grass} geometry={nodes.Circle012_Grass_0.geometry} />
          </group>
          <group position={[-54.61, 0, 6.67]} rotation={[-Math.PI / 2, 0, 0.03]} scale={[4.6, 4.6, 9.14]}>
            <mesh material={materials.Grass} geometry={nodes.Circle005_Grass_0.geometry} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/grass.gltf')
