/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Anskar (https://sketchfab.com/Anskar)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-tree-trunk-d730685ed838498f9d8f7de64989dd9a
title: Low poly Tree Trunk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'

export default function Trunk(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/trunk.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[2, 2, 2]}>
        <mesh material={materials.Wood} geometry={nodes.mesh_0.geometry} />
        <mesh material={materials.Wood_light} geometry={nodes.mesh_1.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/trunk.gltf')
