/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: stveega228 (https://sketchfab.com/stveega228)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vladivostok-low-planet-ae498b827b8044fe927e534e7855d653
title: Vladivostok low planet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'
import { useFrame } from 'react-three-fiber'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/planet.gltf')
  useFrame(() => {
    group.current.rotation.x += 0.0015;
    group.current.rotation.y += 0.0025;
  });

  return (
    <group ref={group} {...props} dispose={null} scale={[3, 3, 3]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={[0.77, 0.77, 0.77]}>
          <mesh material={materials.material_0} geometry={nodes.mesh_0.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_1.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_2.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_3.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_4.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_5.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_6.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_7.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_8.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_9.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_10.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_11.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_12.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_13.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_14.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_15.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_16.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_17.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_18.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_19.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_20.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_21.geometry} />
          <mesh material={materials.material_0} geometry={nodes.mesh_22.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/planet.gltf')
